Snake::Game
readonly int Snake.Game.m_Width
The width.
Referenced by Snake.Game.Game, Snake.Game.GenerateFood, Snake.Game.Lost.
readonly int Snake.Game.m_Height
The height.
Referenced by Snake.Game.Game, Snake.Game.GenerateFood, Snake.Game.Lost.
readonly Snake Snake.Game.m_Snake
The snake.
Referenced by Snake.Game.Game, Snake.Game.GenerateFood, Snake.Game.SnakeHasGrown, Snake.Game.TryEat.
readonly Piece Snake.Game.m_Food
The food.
Referenced by Snake.Game.Game, Snake.Game.TryEat.
readonly Random Snake.Game.m_Rnd
The random.
Referenced by Snake.Game.Game.
Snake.Game.Game(int width, int height)
Constructor.
Jonna, 03-Jul-18. width The width. height The height.
References Snake.Game.m_Food, Snake.Game.m_Height, Snake.Game.m_Rnd, Snake.Game.m_Snake, Snake.Game.m_Width, Snake.Game.Restart.
void Snake.Game.Restart()
Restarts this object.
Jonna, 03-Jul-18.
References Snake.Game.GenerateFood.
Referenced by Snake.Game.Game.
void Snake.Game.Draw(Graphics g)
Draws the given g.
Jonna, 03-Jul-18. g The Graphics to process.
int Snake.Game.GetScore()
Gets the score.
Jonna, 03-Jul-18. The score.
bool Snake.Game.SnakeHasGrown()
Determines if we can snake has grown.
Jonna, 03-Jul-18. True if it succeeds, false if it fails.
References Snake.Snake.Direction, Snake.Game.m_Snake, Snake.Game.TryEat.
Referenced by Snake.Window.OnTimerTick.
bool Snake.Game.Lost()
Losts this object.
Jonna, 03-Jul-18. True if it succeeds, false if it fails.
References Snake.Game.m_Height, Snake.Game.m_Width.
Referenced by Snake.Window.OnTimerTick.
void Snake.Game.ChangeSnakeDIrection(Direction direction)
Change snake d irection.
Jonna, 03-Jul-18. direction The direction.
bool Snake.Game.TryEat(int a, int b)
Attempts to eat an int from the given int.
Jonna, 03-Jul-18. a An int to process. b An int to process. True if it succeeds, false if it fails.
References Snake.Snake.CanEat, Snake.Game.GenerateFood, Snake.Game.m_Food, Snake.Game.m_Snake.
Referenced by Snake.Game.SnakeHasGrown.
void Snake.Game.GenerateFood()
Generates a food.
Jonna, 03-Jul-18.
References Snake.Snake.Contains, Snake.Game.m_Height, Snake.Game.m_Snake, Snake.Game.m_Width.
Referenced by Snake.Game.Restart, Snake.Game.TryEat.