Snake::Window
const int Snake.Window.WIDTH
The width.
Referenced by Snake.Window.Window.
const int Snake.Window.HEIGHT
The height.
Referenced by Snake.Window.Window.
const string Snake.Window.SCORE_STRING
The score string.
Referenced by Snake.Window.UpdateScore.
readonly Color Snake.Window.m_BackgroundColor
The background color.
Referenced by Snake.Window.OnPaint.
readonly Game Snake.Window.m_Game
The game.
Referenced by Snake.Window.OnTimerTick, Snake.Window.Window.
readonly Bitmap Snake.Window.m_GameField
The game field.
Referenced by Snake.Window.OnPaint, Snake.Window.Window.
readonly Graphics Snake.Window.m_GameGraphics
The game graphics.
Referenced by Snake.Window.OnPaint, Snake.Window.Window.
System.ComponentModel.IContainer Snake.Window.components
Required designer variable.
Referenced by Snake.Window.Dispose.
System.Windows.Forms.Timer Snake.Window.m_Timer
System.Windows.Forms.Button Snake.Window.m_RestartBtn
Referenced by Snake.Window.Window.
System.Windows.Forms.Label Snake.Window.scoreLbl
Snake.Window.Window()
Default constructor.
Jonna, 03-Jul-18.
References Snake.Window.HEIGHT, Snake.Window.InitializeComponent, Snake.Window.m_Game, Snake.Window.m_GameField, Snake.Window.m_GameGraphics, Snake.Window.m_RestartBtn, Snake.Piece.SIDE, Snake.Window.WIDTH.
void Snake.Window.UpdateScore()
Updates the score.
Jonna, 03-Jul-18.
References Snake.Window.SCORE_STRING.
Referenced by Snake.Window.OnRestartBtnClick, Snake.Window.OnTimerTick.
void Snake.Window.OnTimerTick(object sender, EventArgs e)
Raises the timer tick event.
Jonna, 03-Jul-18. sender Source of the event. e Event information to send to registered event handlers.
References Snake.Game.Lost, Snake.Window.m_Game, Snake.Game.SnakeHasGrown, Snake.Window.UpdateScore.
void Snake.Window.OnKeyDown(object sender, KeyEventArgs e)
Raises the key event.
Jonna, 03-Jul-18. sender Source of the event. e Event information to send to registered event handlers.
void Snake.Window.OnPaint(object sender, PaintEventArgs e)
Paints this window.
Jonna, 03-Jul-18. sender Source of the event. e Event information to send to registered event handlers.
References Snake.Window.m_BackgroundColor, Snake.Window.m_GameField, Snake.Window.m_GameGraphics.
void Snake.Window.OnRestartBtnClick(object sender, EventArgs e)
Raises the restart button click event.
Jonna, 03-Jul-18. sender Source of the event. e Event information to send to registered event handlers.
References Snake.Window.UpdateScore.
void Snake.Window.InitializeComponent()
Required method for Designer support - do not modify the contents of this method with the code editor.
Referenced by Snake.Window.Window.
override void Snake.Window.Dispose(bool disposing)
Clean up any resources being used.
disposing true if managed resources should be disposed; otherwise, false.
References Snake.Window.components.